local pluginId = (_PLUGIN and _PLUGIN.id) or "LrGeniusAI"

return {
    title = "LrGeniusAI",
    id = 'lrgeniusTagset',
    items = {
        'com.adobe.filename',
        'com.adobe.copyname',
        'com.adobe.folder',
        'com.adobe.dateTimeOriginal',
        'com.adobe.rating',
        'com.adobe.colorLabels',
        'com.adobe.GPS',
        'com.adobe.exposure',
        'com.adobe.exposureProgram',
        'com.adobe.exposureBiasValue',
        'com.adobe.focalLength',
        'com.adobe.isoSpeed',
        'com.adobe.lensModel',
        'com.adobe.model',
        'com.adobe.separator',
        'com.adobe.title',
        { 'com.adobe.caption', height_in_lines = 5 },
        { 'com.adobe.altTextAccessibility', height_in_lines = 5 },
        'com.adobe.separator',
        pluginId .. '.aiModel',
        pluginId .. '.aiLastRun',
        -- _PLUGIN.id .. ".overall_score",
        -- _PLUGIN.id .. ".composition_score",
        -- _PLUGIN.id .. ".lighting_score",
        -- _PLUGIN.id .. ".motiv_score",
        -- _PLUGIN.id .. ".colors_score",
        -- _PLUGIN.id .. ".emotion_score",
        -- { _PLUGIN.id .. ".quality_critique", height_in_lines = 5 },
        { pluginId .. '.photoContext', height_in_lines = 5 },

    },
}
