return {
    title = "LrGeniusAI",
    id = 'lrgeniusTagset',
    items = {
        'com.adobe.filename',
        'com.adobe.copyname',
        'com.adobe.folder',
        'com.adobe.dateTimeOriginal',
        'com.adobe.rating',
        'com.adobe.colorLabels',
        'com.adobe.GPS',
        'com.adobe.exposure',
        'com.adobe.exposureProgram',
        'com.adobe.exposureBiasValue',
        'com.adobe.focalLength',
        'com.adobe.isoSpeed',
        'com.adobe.lensModel',
        'com.adobe.model',
        'com.adobe.separator',
        'com.adobe.title',
        { 'com.adobe.caption', height_in_lines = 5 },
        { 'com.adobe.altTextAccessibility', height_in_lines = 5 },
        'com.adobe.separator',
        -- Custom fields must be plain identifiers (no dots). Use exactly the IDs you declare in MetadataProvider.lua:
        'aiModel',
        'aiProvider',
        'backendFilename',
        'aiLastRun',
        -- 'overall_score',
        -- 'composition_score',
        -- 'lighting_score',
        -- 'motiv_score',
        -- 'colors_score',
        -- 'emotion_score',
        -- { "quality_critique", height_in_lines = 5 },
        { 'photoContext', height_in_lines = 5 },
    },
}
